//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int AccountID { get; set; }
        public int CustomerID { get; set; }
        public int AccountNum { get; set; }
        public string AccountType { get; set; }
        public int PIN { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string LastName2 { get; set; }
        public string FirstName2 { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
